In [7]:
# config jupyter notebook for auto reload
%load_ext autoreload
%autoreload 2

# imports
import numpy as np
import copy
import midterm_project.p1a as p1a
from itertools import chain, product
from collections import deque

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [46]:
s = np.array([[0, 0, 0, 0],
                [1, 1, 1, 1],
                [2, 2, 2, 2],
                [3, 3, 3, 3],
                [4, 4, 4, 4],
                [5, 5, 5, 5]])


o1 = p1a.Rubik(s)

print(o1.state, o1.num_faces, o1.dim)


True
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]] 6 4


In [40]:
new_s1 = copy.deepcopy(o1.state)
o1.rotate_surface(new_s1, 1, 1)
print(o1.state)
print(new_s1)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]


In [39]:
o1.rotate_perimeter(new_s1, ((0, 1, 2, 3), (0, 1, 2, 3)), 2)
print(o1.state)
print(new_s1)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]
[[2 0 0 0]
 [1 3 1 1]
 [2 2 0 2]
 [3 3 3 1]
 [4 4 4 4]
 [5 5 5 5]]


In [52]:
x = o1.move(2, True).move(4, False).move(1, True)
print(x.state)

[[0 0 1 1]
 [1 4 2 2]
 [2 2 3 0]
 [0 3 5 5]
 [3 4 4 3]
 [4 1 5 5]]


In [14]:
result = p1b.bidirectional_search(x)
p1a.show_solution(result)

move 1: face 2 clockwise
move 2: face 1 counter clockwise
move 3: face 3 counter clockwise
move 4: face 2 clockwise
move 5: face 2 clockwise

solution found with 5 moves
number of nodes generated: 72605
number of nodes expanded: 72605
maximum number of nodes in memory: 5


In [1]:
a = [2, 3]
b = [5, 6]
a.append(b)
print(a)

In [5]:
q = deque()
a.append(2)
a.append(3)
a.append(4)
print(5 in a)

False


In [1]:
a = [[1, 2], [3, 4]]
b = [[1, 2], [3, 4]]
print(a == b)

True


In [20]:
q1 = deque()
visited = set()
p1b.add_goals_to_queue(q1, visited)

In [1]:
x = [(i for i in range(5), j for j in range(3))]
print(x)

SyntaxError: invalid syntax (<ipython-input-1-687b3c354742>, line 1)

In [3]:
from itertools import *
print(list(product((1, 2), (3, 4)))) 

[(1, 3), (1, 4), (2, 3), (2, 4)]


In [22]:
ww = deque()
ww.append(1)
ww.append(2)
ww.append(5)
ww.append(4)
for i in ww:
    print(i)

1
2
5
4
